### ISSUE TITLE
Deploy is not currently working.

### ISSUE THREAD

**Issue by sbglasius** [sbglasius/i18n-enums#5]
@jdaugherty mostly a note for you - I'm looking into it, but "real" work has priority 😁

**Comment by jdaugherty** [comment]
@sbglasius Under settings in the pages tab, you need to switch the deploy to come from actions instead of a branch: 

<img width="783" alt="image" src="https://github.com/sbglasius/i18n-enums/assets/2348239/1daa6e77-b5e2-498a-b30b-38e156b7d39c">

Have you done this?

**Comment by sbglasius** [comment]
@jdaugherty sorry for the long wait. I'm bogged down with paying work. But now it appears to be working

**Comment by sbglasius** [comment]
The new coordinate is 

```
dk.glasius:i18n-enums:5.0.0
```
